# Generated by Django 6.0.2 on 2026-05-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('family', 'Семейный чат'), ('personal', 'Личный чат'), ('group', 'Групповой чат')], default='personal', max_length=10, verbose_name='Тип чата'),
        ),
    ]
