# Generated by Django 6.0.2 on 2026-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_name_alter_chat_chat_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-is_pinned', '-updated_at', '-created_at'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_main_family_chat',
            field=models.BooleanField(default=False, verbose_name='Основной семейный чат'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплён'),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('family', 'Групповой чат'), ('personal', 'Личный чат')], default='personal', max_length=10, verbose_name='Тип чата'),
        ),
    ]
