# Generated by Django 6.0.2 on 2026-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_options_remove_chat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_photos/', verbose_name='Фото чата'),
        ),
    ]
