# Generated by Django 6.0.2 on 2026-05-25 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_family_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tasks', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Семейная задача',
                'verbose_name_plural': 'Семейные задачи',
                'ordering': ['is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('is_done', models.BooleanField(default=False, verbose_name='Куплено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_shopping_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто купил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shopping_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Список продуктов',
                'ordering': ['is_done', '-created_at'],
            },
        ),
    ]
