# Generated by Django 6.0.2 on 2026-05-01 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('sent', 'Отправлен'), ('received', 'Получен'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='sent', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отмены')),
                ('confirmed_by', models.ManyToManyField(blank=True, related_name='confirmed_sos', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердили получение')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_signals', to='families.family', verbose_name='Семья')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_signals', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'SOS сигнал',
                'verbose_name_plural': 'SOS сигналы',
                'ordering': ['-created_at'],
            },
        ),
    ]
