# Generated by Django 6.0.2 on 2026-05-23 19:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип категории')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандартная категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_finance_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Категория финансов',
                'verbose_name_plural': 'Категории финансов',
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FinanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название цели')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('scope', models.CharField(choices=[('personal', 'Личная цель'), ('family', 'Общая цель')], default='personal', max_length=20, verbose_name='Тип цели')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Накоплено')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Целевая сумма')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Выполнена')], default='active', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_finance_goals', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('members', models.ManyToManyField(blank=True, related_name='finance_goal_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Участники цели')),
            ],
            options={
                'verbose_name': 'Финансовая цель',
                'verbose_name_plural': 'Финансовые цели',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceGoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата пополнения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goal_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Кто пополнил')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finance.financegoal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Пополнение цели',
                'verbose_name_plural': 'Пополнения целей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название ячейки')),
                ('type', models.CharField(choices=[('personal', 'Личный бюджет'), ('joint', 'Совместный бюджет'), ('collection', 'Сбор / цель')], default='joint', max_length=20, verbose_name='Тип ячейки')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_finance_spaces', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_spaces', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Финансовая ячейка',
                'verbose_name_plural': 'Финансовые ячейки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Название операции')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='finance.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_finance_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('finance_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='finance.financespace', verbose_name='Финансовая ячейка')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financegoal',
            name='finance_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='finance.financespace', verbose_name='Финансовая ячейка'),
        ),
        migrations.AddField(
            model_name='category',
            name='finance_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.financespace', verbose_name='Финансовая ячейка'),
        ),
        migrations.CreateModel(
            name='FinanceSpaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('member', 'Участник')], default='member', max_length=20, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_finance_space_members', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
                ('finance_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_members', to='finance.financespace', verbose_name='Финансовая ячейка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_space_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник финансовой ячейки',
                'verbose_name_plural': 'Участники финансовых ячеек',
            },
        ),
        migrations.AddField(
            model_name='financespace',
            name='members',
            field=models.ManyToManyField(related_name='finance_spaces', through='finance.FinanceSpaceMember', through_fields=('finance_space', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('finance_space', 'type', 'title'), name='unique_finance_category_per_space_type'),
        ),
        migrations.AddConstraint(
            model_name='financespacemember',
            constraint=models.UniqueConstraint(fields=('finance_space', 'user'), name='unique_finance_space_member'),
        ),
    ]
