# Generated by Django 6.0.2 on 2026-05-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('category_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], max_length=10, verbose_name='Тип')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FamilyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накоплено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Семейная цель',
                'verbose_name_plural': 'Семейные цели',
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='finance.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
