# Generated by Django 6.0.2 on 2026-05-11 20:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип категории')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандартная категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_finance_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Категория финансов',
                'verbose_name_plural': 'Категории финансов',
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FamilyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название цели')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Накоплено')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Целевая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_family_goals', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_goal', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Семейная финансовая цель',
                'verbose_name_plural': 'Семейные финансовые цели',
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='finance.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_finance_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='families.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('family', 'type', 'title'), name='unique_finance_category_per_family_type'),
        ),
    ]
