# Generated by Django 6.0.2 on 2026-05-01 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('doc_type', models.CharField(choices=[('personal', 'Личные'), ('medical', 'Медицина'), ('family', 'Семейные'), ('property', 'Имущество'), ('education', 'Образование'), ('other', 'Другое')], default='other', max_length=10, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('access', models.CharField(choices=[('owner', 'Только я'), ('family', 'Всей семье'), ('selected', 'Выбранным участникам')], default='owner', max_length=10, verbose_name='Доступ')),
                ('is_family_doc', models.BooleanField(default=False, verbose_name='Общий документ семьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='families.family', verbose_name='Семья')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_documents', to=settings.AUTH_USER_MODEL, verbose_name='Доступ открыт для')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
