# Generated by Django 6.0.2 on 2026-05-24 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTreePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unknown', 'Не указано')], default='unknown', max_length=20, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('photo_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на фото')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tree_persons', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_persons', to='families.family', verbose_name='Семья')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_tree_person', to=settings.AUTH_USER_MODEL, verbose_name='Связанный аккаунт')),
            ],
            options={
                'verbose_name': 'Человек в семейном древе',
                'verbose_name_plural': 'Люди в семейном древе',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('married', 'Брак'), ('relationship', 'Отношения'), ('divorced', 'Развод'), ('widowed', 'Вдовство')], default='relationship', max_length=30, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='families.family', verbose_name='Семья')),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_first', to='familytree.familytreeperson', verbose_name='Партнёр 1')),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_second', to='familytree.familytreeperson', verbose_name='Партнёр 2')),
            ],
            options={
                'verbose_name': 'Партнёрская связь',
                'verbose_name_plural': 'Партнёрские связи',
            },
        ),
        migrations.CreateModel(
            name='FamilyTreePersonalLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Кто этот человек для пользователя')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_labels', to='familytree.familytreeperson', verbose_name='Человек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_personal_labels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Личная подпись человека',
                'verbose_name_plural': 'Личные подписи людей',
                'unique_together': {('user', 'person')},
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('biological', 'Биологическая связь'), ('adoptive', 'Приёмная связь'), ('guardian', 'Опекунство'), ('step', 'Отчим / мачеха')], default='biological', max_length=30, verbose_name='Тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='familytree.familytreeperson', verbose_name='Ребёнок')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_child_relations', to='families.family', verbose_name='Семья')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='familytree.familytreeperson', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Связь родитель-ребёнок',
                'verbose_name_plural': 'Связи родитель-ребёнок',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
