# Generated by Django 6.0.2 on 2026-05-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, null=True, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='familytree/', verbose_name='Фото')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О человеке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_tree_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_nodes', to='families.family', verbose_name='Семья')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_node', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='familytree.familytreenode', verbose_name='Родитель')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='familytree.familytreenode', verbose_name='Супруг(а)')),
            ],
            options={
                'verbose_name': 'Элемент древа',
                'verbose_name_plural': 'Элементы древа',
            },
        ),
    ]
