# Generated by Django 6.0.2 on 2026-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytreeperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_tree/photos/', verbose_name='Фото'),
        ),
    ]
