# Generated by Django 6.0.2 on 2026-06-12 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('familytree', '0002_familytreeperson_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familytreepersonallabel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parentchildrelation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='familytreeperson',
            index=models.Index(fields=['family', 'id'], name='familytree__family__ec4ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='familytreeperson',
            index=models.Index(fields=['family', 'linked_user'], name='familytree__family__b6b480_idx'),
        ),
        migrations.AddIndex(
            model_name='familytreeperson',
            index=models.Index(fields=['family', 'last_name', 'first_name'], name='familytree__family__0fc47e_idx'),
        ),
        migrations.AddIndex(
            model_name='familytreepersonallabel',
            index=models.Index(fields=['user', 'person'], name='familytree__user_id_733029_idx'),
        ),
        migrations.AddIndex(
            model_name='familytreepersonallabel',
            index=models.Index(fields=['person'], name='familytree__person__6d804c_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['family', 'parent'], name='familytree__family__8c2f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['family', 'child'], name='familytree__family__10f418_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['family', 'parent', 'child'], name='familytree__family__34a639_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['family', 'partner1'], name='familytree__family__7dac10_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['family', 'partner2'], name='familytree__family__dd428b_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['family', 'partner1', 'partner2'], name='familytree__family__aacbb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='familytreepersonallabel',
            constraint=models.UniqueConstraint(fields=('user', 'person'), name='unique_family_tree_personal_label'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_family_tree_parent_child_relation'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='family_tree_parent_is_not_child'),
        ),
        migrations.AddConstraint(
            model_name='partnership',
            constraint=models.CheckConstraint(condition=models.Q(('partner1', models.F('partner2')), _negated=True), name='family_tree_partner_is_not_self'),
        ),
        migrations.AddConstraint(
            model_name='partnership',
            constraint=models.UniqueConstraint(fields=('family', 'partner1', 'partner2'), name='unique_family_tree_partnership'),
        ),
    ]
