# Generated by Django 6.0.2 on 2026-06-12 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('familytree', '0003_alter_familytreepersonallabel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Связь брат/сестра',
                'verbose_name_plural': 'Связи брат/сестра',
            },
        ),
        migrations.RemoveConstraint(
            model_name='familytreepersonallabel',
            name='unique_family_tree_personal_label',
        ),
        migrations.RemoveConstraint(
            model_name='parentchildrelation',
            name='unique_family_tree_parent_child_relation',
        ),
        migrations.RemoveConstraint(
            model_name='parentchildrelation',
            name='family_tree_parent_is_not_child',
        ),
        migrations.RemoveConstraint(
            model_name='partnership',
            name='family_tree_partner_is_not_self',
        ),
        migrations.RemoveConstraint(
            model_name='partnership',
            name='unique_family_tree_partnership',
        ),
        migrations.RemoveIndex(
            model_name='familytreeperson',
            name='familytree__family__ec4ee2_idx',
        ),
        migrations.RemoveIndex(
            model_name='familytreeperson',
            name='familytree__family__b6b480_idx',
        ),
        migrations.RemoveIndex(
            model_name='familytreeperson',
            name='familytree__family__0fc47e_idx',
        ),
        migrations.RemoveIndex(
            model_name='familytreepersonallabel',
            name='familytree__user_id_733029_idx',
        ),
        migrations.RemoveIndex(
            model_name='familytreepersonallabel',
            name='familytree__person__6d804c_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentchildrelation',
            name='familytree__family__8c2f2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentchildrelation',
            name='familytree__family__10f418_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentchildrelation',
            name='familytree__family__34a639_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnership',
            name='familytree__family__7dac10_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnership',
            name='familytree__family__dd428b_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnership',
            name='familytree__family__aacbb4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='familytreepersonallabel',
            unique_together={('user', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='parentchildrelation',
            unique_together={('parent', 'child')},
        ),
        migrations.AddField(
            model_name='siblingrelation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations', to='families.family', verbose_name='Семья'),
        ),
        migrations.AddField(
            model_name='siblingrelation',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations_as_first', to='familytree.familytreeperson', verbose_name='Человек 1'),
        ),
        migrations.AddField(
            model_name='siblingrelation',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations_as_second', to='familytree.familytreeperson', verbose_name='Человек 2'),
        ),
    ]
