# Generated by Django 6.0.2 on 2026-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chronic_diseases',
            field=models.TextField(blank=True, default='', verbose_name='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Имя экстренного контакта'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон экстренного контакта'),
        ),
        migrations.AddField(
            model_name='user',
            name='medications',
            field=models.TextField(blank=True, default='', verbose_name='Принимаемые лекарства'),
        ),
    ]
