# Generated by Django 6.0.2 on 2026-05-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_last_seen_userpresence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpresence',
            options={'verbose_name': 'Онлайн-статус пользователя', 'verbose_name_plural': 'Онлайн-статусы пользователей'},
        ),
    ]
